package dk.skancode.barcodescannermodule.event

import android.nfc.Tag
import dk.skancode.barcodescannermodule.gs1.Gs1Object

fun interface TypedEventHandler {
    fun onEvent(e: TypedEvent)
}

sealed class TypedEvent {
    data class BarcodeEvent(val barcode1: String?, val barcode2: String?, val barcodeType: BarcodeType, val ok: Boolean): TypedEvent()
    data class Gs1Event(val ok: Boolean, val isGs1: Boolean, val gs1: Gs1Object, val barcode: String?, val barcodeType: BarcodeType): TypedEvent()
    data class NfcEvent(val tag: Tag?): TypedEvent()
}

/**
 * This type is based on the barcode types specified in [Newland Android PDA API Handbook](https://www.newland-id.com/sites/default/files/documents/2024-02/newland_android_pda_api_handbook_v1.0.6.pdf) on page 30.
 */
data class BarcodeType(val name: String) {
    companion object {
        val UNKNOWN = BarcodeType("UNKNOWN")
        val CODE128 = BarcodeType("Code 128")
        val UCCEAN128 = BarcodeType("UCC/EAN/GS1 128")
        val AIM128 = BarcodeType("AIM 128")
        val GS1_128 = BarcodeType("GS1 128")
        val ISBT128 = BarcodeType("ISBT 128")
        val EAN8 = BarcodeType("EAN8")
        val EAN13 = BarcodeType("EAN13")
        val UPCE = BarcodeType("UPCE")
        val UPCA = BarcodeType("UPCA")
        val ISBN = BarcodeType("ISBN")
        val ISSN = BarcodeType("ISSN")
        val CODE39 = BarcodeType("Code 39")
        val CODE93 = BarcodeType("Code 93")
        val CODE93I = BarcodeType("Code 93I")
        val CODABAR = BarcodeType("CODABAR")
        val ITF = BarcodeType("ITF")
        val ITF6 = BarcodeType("ITF6")
        val ITF14 = BarcodeType("ITF14")
        val DPLEITCODE = BarcodeType("DPLEITCODE")
        val DPIDENTCODE = BarcodeType("DPIDENTCODE")
        val CHNPOST25 = BarcodeType("CHNPOST 25")
        val STANDARD25 = BarcodeType("STANDARD 25")
        val IATA25 = BarcodeType("IATA 25")
        val MATRIX25 = BarcodeType("MATRIX 25")
        val INDUSTRIAL25 = BarcodeType("INDUSTRIAL 25")
        val COOP25 = BarcodeType("COOP25")
        val CODE11 = BarcodeType("Code 11")
        val MSIPLESSEY = BarcodeType("MSIPLESSEY")
        val PLESSEY = BarcodeType("PLESSEY")
        val RSS14 = BarcodeType("RSS14")
        val RSSLIMITED = BarcodeType("RSS LIMITED")
        val RSSEXPANDED = BarcodeType("RSS EXPANDED")
        val TELEPEN = BarcodeType("TELEPEN")
        val CHANNELCODE = BarcodeType("CHANNELCODE")
        val CODE32 = BarcodeType("Code 32")
        val CODEZ = BarcodeType("CODEZ")
        val CODABLOCKF = BarcodeType("Codablock F")
        val CODABLOCKA = BarcodeType("Codablock A")
        val CODE49 = BarcodeType("Code 49")
        val CODE16K = BarcodeType("Code 16K")
        val HIBC128 = BarcodeType("HIBC 128")
        val HIBC39 = BarcodeType("HIBC 39")
        val RSSFAMILY = BarcodeType("RSS FAMILY")
        val TRIOPTIC_CODE39 = BarcodeType("Trioptic Code 39")
        val UPC_E1 = BarcodeType("UPC E1")
        val PDF417 = BarcodeType("PDF417")
        val MICROPDF = BarcodeType("MICROPDF")
        val QRCODE = BarcodeType("QRCODE")
        val MICROQR = BarcodeType("MICROQR")
        val AZTEC = BarcodeType("AZTEC")
        val DATAMATRIX = BarcodeType("DATAMATRIX")
        val MAXICODE = BarcodeType("MAXICODE")
        val CSCODE = BarcodeType("CSCODE")
        val GRIDMATRIX = BarcodeType("GRIDMATRIX")
        val EARMARK = BarcodeType("Earmark")
        val VERICODE = BarcodeType("VeriCode")
        val CCA = BarcodeType("CCA")
        val CCB = BarcodeType("CCB")
        val CCC = BarcodeType("CCC")
        val COMPOSITE = BarcodeType("COMPOSITE")
        val HIBCAZT = BarcodeType("HIBC AZT")
        val HIBCDM = BarcodeType("HIBC DM")
        val HIBCMICROPDF = BarcodeType("HIBC MICRO PDF")
        val HIBCQR = BarcodeType("HIBC QR")
        val DOTCODE = BarcodeType("DOTCODE")
        val POSTNET = BarcodeType("POSTNET")
        val ONECODE = BarcodeType("ONECODE")
        val RM4SCC = BarcodeType("RM4SCC")
        val PLANET = BarcodeType("PLANET")
        val KIX = BarcodeType("KIX")
        val APCUSTOM = BarcodeType("AP CUSTOM")
        val APREDIRECT = BarcodeType("AP REDIRECT")
        val APREPLYPAID = BarcodeType("AP REPLY PAID")
        val APROUTING = BarcodeType("AP ROUTING")
        val NUMOCRB = BarcodeType("NUMOCRB")
        val PASSPORT = BarcodeType("PASSPORT")
        val TD1 = BarcodeType("TD1")
        val PRIVATE = BarcodeType("PRIVATE")
        val ZZCODE = BarcodeType("ZZ Code")
        val AUSTRALIANPOSTAL = BarcodeType("AUSTRALIANPOSTAL")
        val CANADIANPOSTAL = BarcodeType("CANADIANPOSTAL")
        val CHINESE2OF5 = BarcodeType("CHINESE2OF5")
        val COMPOSITEAB = BarcodeType("COMPOSITEAB")
        val COMPOSITEC = BarcodeType("COMPOSITEC")
        val DECODERSIGNATURE = BarcodeType("DECODERSIGNATURE")
        val DISCRETE2OF5 = BarcodeType("DISCRETE2OF5")
        val DUTCHPOSTAL = BarcodeType("DUTCHPOSTAL")
        val FINNISHPOSTAL4S = BarcodeType("FINNISHPOSTAL4S")
        val GS1DATABAR = BarcodeType("GS1DATABAR")
        val GS1DATABARLIMITED = BarcodeType("GS1DATABARLIMITED")
        val GS1DATABAREXPANDED = BarcodeType("GS1DATABAREXPANDED")
        val GS1DATAMATRIX = BarcodeType("GS1DATAMATRIX")
        val GS1QRCODE = BarcodeType("GS1QRCODE")
        val HANXIN = BarcodeType("HANXIN")
        val INTERLEAVED2OF5 = BarcodeType("INTERLEAVED2OF5")
        val JAPANESEPOSTAL = BarcodeType("JAPANESEPOSTAL")
        val KOREAN3OF5 = BarcodeType("KOREAN3OF5")
        val MACROPDF = BarcodeType("MACROPDF")
        val MAILMARK = BarcodeType("MAILMARK")
        val MATRIX2OF5 = BarcodeType("MATRIX2OF5")
        val MICRE13B = BarcodeType("MICRE13B")
        val MACROMICROPDF = BarcodeType("MACROMICROPDF")
        val MSI = BarcodeType("MSI")
        val OCRA = BarcodeType("OCRA")
        val OCRB = BarcodeType("OCRB")
        val TLC39 = BarcodeType("TLC39")
        val USCURRENCY = BarcodeType("USCURRENCY")
        val USPOSTNET = BarcodeType("USPOSTNET")
        val USPLANET = BarcodeType("USPLANET")
        val USPOSTAL = BarcodeType("USPOSTAL")
        val UKPOSTAL = BarcodeType("UKPOSTAL")
        val US4STATEFICS = BarcodeType("US4STATEFICS")
        val US4STATE = BarcodeType("US4STATE")
    }
    /*
     */
}